"""图表内文本字典与语言检测（zh/en 双语）。

文本语言默认跟随数据语言自动检测，用户可通过 lang 参数强制指定。
chart_generator / renderers / template 三层共用本模块，不得各自维护文案副本。
"""

import re
import pandas as pd
from typing import Dict, Optional, Tuple

# 中文字符范围（CJK 统一表意文字）
_CJK_RE = re.compile(r'[\u4e00-\u9fff]')

# 图表内文本字典：series name / tooltip / HTML 按钮 / footer 等。
TEXTS: Dict[str, Dict[str, str]] = {
    'zh': {
        'default_title': '数据图表',
        'default_annotation': '本图展示 {n} 条数据。',
        'series_heatmap': '热力图',
        'series_treemap': '树图',
        'series_graph': '关系图',
        'series_boxplot': '箱线图',
        'series_outliers': '异常值',
        'series_gauge': '仪表盘',
        'series_sankey': '桑基图',
        'series_funnel': '漏斗图',
        'series_sunburst': '旭日图',
        'series_wordcloud': '词云',
        'series_bubble': '气泡图',
        'series_venn': '维恩图',
        'series_mindmap': '思维导图',
        'series_orgchart': '组织架构图',
        'series_liquid': '水波图',
        'series_pareto': '累计百分比',
        'series_uncategorized': '未分类',
        'axis_frequency': '频数',
        'rename_hint': '点击名称可修改；轴名还可在图上直接拖拽调整位置（保存图片时均生效）',
        'rename_group_series': '系列',
        'rename_group_axis': '轴',
        'tooltip_no_data': '无数据',
        'btn_save': '保存图片',
        'btn_fullscreen': '全屏',
        'scroll_hint': '数据点较多，可拖动图内滑块、横向滚动或点击全屏查看完整内容',
        'edit_hint': '双击标题可编辑',
        'title_updated': '标题已更新，保存图片时将使用新标题',
        'footer': '由 Smart Charts 生成',
        'comment_download_name': '保存图片时使用的文件名，随标题内联编辑动态更新',
        'comment_title_edit': '标题内联编辑：双击标题可直接修改，Enter 确认，Escape 取消',
        'comment_title_sync': '编辑后同步更新 ECharts 图表标题和保存图片的文件名',
    },
    'en': {
        'default_title': 'Data Chart',
        'default_annotation': 'This chart shows {n} rows of data.',
        'series_heatmap': 'Heatmap',
        'series_treemap': 'Treemap',
        'series_graph': 'Graph',
        'series_boxplot': 'Boxplot',
        'series_outliers': 'Outliers',
        'series_gauge': 'Gauge',
        'series_sankey': 'Sankey',
        'series_funnel': 'Funnel',
        'series_sunburst': 'Sunburst',
        'series_wordcloud': 'Word Cloud',
        'series_bubble': 'Bubble',
        'series_venn': 'Venn',
        'series_mindmap': 'Mind Map',
        'series_orgchart': 'Org Chart',
        'series_liquid': 'Liquid',
        'series_pareto': 'Cumulative %',
        'series_uncategorized': 'Uncategorized',
        'axis_frequency': 'Frequency',
        'rename_hint': 'Click a name to rename; axis names can also be dragged on the chart (applied when saving image)',
        'rename_group_series': 'Series',
        'rename_group_axis': 'Axis',
        'tooltip_no_data': 'No data',
        'btn_save': 'Save Image',
        'btn_fullscreen': 'Fullscreen',
        'scroll_hint': 'Many data points: drag the slider, scroll horizontally, or click fullscreen to view all',
        'edit_hint': 'Double-click title to edit',
        'title_updated': 'Title updated, new title will be used when saving image',
        'footer': 'Generated by Smart Charts',
        'comment_download_name': 'Download filename for saving images, updates with inline title edit',
        'comment_title_edit': 'Inline title edit: double-click to edit, Enter to confirm, Escape to cancel',
        'comment_title_sync': 'After edit, sync ECharts chart title and save-image filename',
    },
}


def detect_language(df: pd.DataFrame) -> str:
    """检测 DataFrame 的语言：检查列名和前若干行字符串值中的中文字符占比。

    中文字符占字母类字符的比例 > 5% 即判定为中文，否则为英文。
    """
    chars = ''.join(str(c) for c in df.columns)
    for col in df.columns:
        if df[col].dtype == 'object' or pd.api.types.is_string_dtype(df[col]):
            chars += ''.join(str(v) for v in df[col].head(20).tolist() if v is not None)
    alpha_count = sum(1 for c in chars if c.isalpha())
    if alpha_count == 0:
        return 'en'
    chinese_count = sum(1 for c in chars if _CJK_RE.match(c))
    return 'zh' if chinese_count / alpha_count > 0.05 else 'en'


def get_texts(lang: Optional[str], df: pd.DataFrame) -> Tuple[Dict[str, str], str]:
    """根据 lang 参数或数据自动检测结果返回 (文本字典, 实际生效的语言)。

    lang 为 None 或非法值时按数据自动检测；返回实际语言供 template 层
    显式决定 <html lang>，不再做字典身份比较。
    """
    if lang not in TEXTS:
        lang = detect_language(df)
    return TEXTS[lang], lang
